### ISSUE TITLE
Sunrise/sunset function

### ISSUE THREAD

**Issue by animalito** [dssg/energywise#3]
Return position of sun at any given date/time

**Comment by cameliasimoiu** [comment]
require state to be given. 
city is optional
if no city is given, assume state capital

**Comment by cameliasimoiu** [comment]
use ephem library (python)

**Comment by cameliasimoiu** [comment]
potential adjustment: make timezone in stateDB.pickle correspond to pytz library codes, so date taken into function is automatically assigned the local timezone
